version: "3"

services:  
    db:
        image: mongo:3.6.18-xenial

    server:
        build: ./server
        restart: always
        ports:
            - "8080:8080"
        depends_on: 
            - db
    
